name: Deploy Appunti Client
on:
    push:
        branches:
            - master
jobs:
    build:
        env:
          CI: false
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Deploy to Vercel
              uses: amondnet/vercel-action@v20
              run: |
                  git config user.email ${{ secrets.EMAIL }}
                  git config user.name ${{ secrets.USERNAME }}
                  git remote set-url origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ secrets.USERNAME }}/${{ secrets.REPO_NAME }}.git
              with:
                vercel-token: ${{ secrets.VERCEL_TOKEN }}
                github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                vercel-args: '--prod'
                vercel-org-id: ${{ secrets.ORG_ID}}
                vercel-project-id: ${{ secrets.PROJECT_ID}}
                vercel-project-name: appunti
                working-directory: ./